### ISSUE TITLE
getDesignDocuments error with Couchbase 3

### ISSUE THREAD

**Issue by nickcaus** [brett19/php-couchbase#1]
Hello. Looks like getDesignDocuments function returns:

Notice: Undefined index: meta in [CouchbaseNative]/CouchbaseBucketManager.class.php on line 53
Notice: Undefined index: json in [CouchbaseNative]/CouchbaseBucketManager.class.php on line 54
Notice: Undefined index: meta in [CouchbaseNative]/CouchbaseBucketManager.class.php on line 53
Notice: Undefined index: json in [CouchbaseNative]/CouchbaseBucketManager.class.php on line 54

Is this lib version compatible with Couchbase server 3 ?

Looks like in 3 version you have additionally doc/controllers structure https://www.dropbox.com/s/mfk9d304ugcrzcu/Screenshot%202014-12-12%2018.55.10.png?dl=0

**Comment by JordyMoos** [comment]
This should be fixed with:
https://github.com/brett19/php-couchbase/pull/2

**Comment by brett19** [comment]
#2 has been accepted as https://github.com/brett19/php-couchbase/commit/0f35f185aeb6f19eb9349cbb14b722fe70fb14f8.
