### ISSUE TITLE
libcouchbase with createBucket

### ISSUE THREAD

**Issue by cyb3rd4d** [brett19/php-couchbase#16]
Hello

I am experiencing an issue with the method CouchbaseClusterManager::createBucket:

FATAL ERROR:
    libcouchbase experienced an unrecoverable error and terminates the program
    to avoid undefined behavior.
    The program should have generated a "corefile" which may used
    to gather more information about the problem.
    If your system doesn't create "corefiles" I can tell you that the
    assertion failed in /tmp/buildd/libcouchbase-2.5.4/src/bucketconfig/confmon.c at line 293

Here is the PHP code:

``` php
$adminUsername = 'Administrator';
$adminPassword = 'mySuperP@ssw0rd';
$cluster = new \CouchbaseCluster('couchbase://localhost', $adminUsername, $adminPassword);
$bucketManager = $cluster->manager($adminUsername, $adminPassword);

$bucketManager->createBucket('plop', [
    'authType' => 'sasl',
    'bucketType' => 'couchbase',
    'flushEnabled' => true,
    'ramQuotaMB' => 200
 ]);
```

The documentation of the PHP client does not mention anything about the method options. So I tried to use the options described in the REST API documentation.

System informations:
- OS: Ubuntu 14.04
- libcouchbase-dev: 2.5.4-1 (from the APT repository)
- php couchbase extension: built from sources (dev-master)
- php version: 5.6.16-1 from the Ondrej PPA (http://ppa.launchpad.net/ondrej/php5-5.6/ubuntu)

Thank you for your help.

**Comment by brett19** [comment]
Please see: https://issues.couchbase.com/browse/PCBC-375

**Comment by cyb3rd4d** [comment]
OK thank you.
