### ISSUE TITLE
Configurable error mode

### ISSUE THREAD

**Issue by EVODelavega** [brett19/php-couchbase#8]
I was wondering if there were any plans to make the extensions' behaviour configurable in the event of certain errors. For example: when retrieving a bunch of documents in a loop like so:

``` php
$docs = [];
for ($i=0;$i<100;++$i)
    $docs[] = $bucket->get('document::' . $i);
```

At the moment, the extension throws an exception whenever a document doesn't exist. It would be useful, IMO, to call a method that changes this behaviour (ie, have the `get` call return `null` when a document is not found instead).

I've taken a quick look at the code, and I'm happy to implement this feature myself (so far, I've only added 2 methods: https://github.com/EVODelavega/php-couchbase/tree/remote-master), but the way this extension is built is a bit odd in places (with the stubs being an actual integral part of the extension and all that...).
Is there any documentation available for people wanting to contribute to this project?

Thanks

**Comment by brett19** [comment]
Hey EVODelavega,

The main reason for not implementing this functionality is that `null`, `false`, etc... are all perfectly valid document values.  This means that it would potentially cause conflicts when detecting the existence of a document!

Cheers, Brett

**Comment by brett19** [comment]
However, I should add that if you are interested in this functionality, and you know for your own use-case that this collision could not occur, you can easily provide a wrapper function for the get call which implements this logic by wrapping the underlying Bucket get call with an exception handler.

Cheers, Brett

**Comment by EVODelavega** [comment]
@brett19 We're currently using a wrapper service that handles the exceptions for us, of course. The main reason for us wanting the silent failing get calls now is so we can extensively, and reliably test a couple of scenarios and being able to accurately determine the overhead of the exceptions that are being caught and silenced by the wrapper.

I do understand the reasoning behind `null` and `false` being valid return values, but a successful `get` call returns a CouchbaseMetaDoc instance, which is easily distinguishable from a regular `null` value, so it would still be possible to trace faulty `get` calls that way
